- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'MSDN Platforms(88b61a3d-c1e3-459b-8ef2-f85a9c975340)'
    Action: 'Stop Azure App Service'
    WebAppName: 'homini'
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'MSDN Platforms(88b61a3d-c1e3-459b-8ef2-f85a9c975340)'
    Action: 'Start Azure App Service'
    WebAppName: 'homini'
